#pragma once

#include <string>
#include <iostream>

#include <boost/graph/adjacency_list.hpp>

struct Vertex
{
    std::string path;
    std::string file;
};

struct Edge
{
};

class Graph
{
public:
    using graph_type = boost::adjacency_list<boost::listS, boost::vecS, boost::directedS, Vertex, Edge>;
    using vertex_descriptor = boost::graph_traits<graph_type>::vertex_descriptor;

public:
    /**
     *  A file generated by g++ -H.
     */
    void loadFromFile(std::string const& file);

    /**
     *  A stream containing stuff generated by g++ -H.
     */
    void loadFromStream(std::istream& stream);

    /**
     *  Create a graphviz dot file.
     */
    void toDotFile(std::string const& fileName);

private:
    graph_type graph_;
};
